# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
  - name: doDeployment
    displayName: Deploy To Environment 
    default: true
    type: boolean
  - name: targetEnvironment
    displayName: Target Environment 
    type: string
    default: Test
    values:
    - Dev
    - Test
  - name: dataDeploymentType
    displayName: Data Deployment Type
    type: string
    default: Import
    values:
    - None
    - Import
    - DropCollectionAndImport

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'  
  - group: Azure.Environment.Nucleus.Acc.Net.Api
    
steps:
- checkout: self
  clean: true
  persistCredentials: true
  fetchDepth: 0

- task: UseDotNet@2
  displayName: 'Install .Net 6.0 SDK'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'       
                  
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    #versionSpec: '5.8.1'    
    preferLatestVersion: true

- task: gitversion/execute@0
  displayName: Use GitVersion
  inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'
    
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: DotNetCoreCLI@2
  displayName: 'Building ${{ parameters.targetEnvironment }}'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: >
      --configuration $(buildConfiguration) 
      --nologo 
      --property:DeployOnBuild=true 
      --property:WebPublishMethod=Package 
      --property:PackageAsSingleFile=true 
      --property:SkipInvalidConfigurations=true 
      --property:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" 
      --property:DeployIisAppPath="Default Web Site"
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests as $(buildConfiguration)
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: >
      --configuration $(buildConfiguration) 
      --no-build 
      --no-restore 
      --nologo 
      --filter "TestCategory=Unit|TestCategory=Simulate" 
      --collect:"XPlat Code Coverage" 
      --settings "$(Build.SourcesDirectory)\.runsettings"
    publishTestResults: true
          
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Reports'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: $(Agent.TempDirectory)/TestResults/Coverage/Reports/Cobertura.xml
    failIfCoverageEmpty: false 

- task: AzureRmWebAppDeployment@4
  condition: and(succeeded(), eq('${{ parameters.doDeployment }}', true))
  displayName: 'Deploying API to ${{ parameters.targetEnvironment }}'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'AppDev Project Nucleus'
    appType: 'webApp'
    WebAppName: '$(${{parameters.targetEnvironment}}-ServerName)'
    packageForLinux: '$(build.artifactStagingDirectory)\WebApp.zip'

- task: DotNetCoreCLI@2
  condition: and(succeeded(), eq('${{ parameters.doDeployment }}', true), ne('${{ parameters.dataDeploymentType }}', 'None'))
  displayName: 'Deploying Data to ${{ parameters.targetEnvironment }}'
  inputs:
    command: 'run'
    projects: 'Tools\Nucleus.Dataloader.Cli'
    arguments: >
      --configuration $(buildConfiguration) 
      --no-build 
      --no-restore 
      --nologo 
      --
      --SourcePath="$(Build.SourcesDirectory)\Conf\MongoDb\SampleData"
      --Action=${{ parameters.dataDeploymentType }}
      --ConnectionString="$(${{parameters.targetEnvironment}}-MongoDatabase__ConnectionString)"
      --DatabaseName="$(${{parameters.targetEnvironment}}-MongoDatabase__DatabaseName)"

- task: PowerShell@2
  displayName: Set Version Variables
  name: setVersionVar
  inputs:
    targetType: 'inline'
    script: |
            $fullSemVerLower = "$(fullSemVer)".ToLower()            
            Write-Host "FullSemVer=$(fullSemVer)"        
            Write-Host "FullSemVerLower=$fullSemVerLower"
            Write-Host "AssemblySemVer=$(AssemblySemVer)"
            Write-Host "AssemblySemFileVer=$(assemblySemFileVer)"
            Write-Host "InformationalVersion=$(InformationalVersion)"
            Write-Host "##vso[build.updatebuildnumber]$(fullSemVer)"
            Write-Host "##vso[task.setvariable variable=FullSemVer;isOutput=true]$(fullSemVer)"
            Write-Host "##vso[task.setvariable variable=FullSemVerLower;isOutput=true]$fullSemVerLower"    
            Write-Host "##vso[task.setvariable variable=InformationalVersion;isOutput=true]$(InformationalVersion)"
            Write-Host "##vso[task.setvariable variable=AssemblySemVer;isOutput=true]$(AssemblySemVer)"
            Write-Host "##vso[task.setvariable variable=AssemblySemFileVer;isOutput=true]$(AssemblySemFileVer)"
            Write-Host "##vso[task.setvariable variable=BuildVersionTag;isOutput=true]Core-v$(fullSemVer)"
                  
- task: tagBuildOrRelease@0
  displayName: 'Tag Build'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    type: 'Build'
    tags: '$(BuildVersionTag)'
    
# https://dina-muscanell.com/blog/set-git-tags-with-azure-devops/
# https://stackoverflow.com/questions/59226055/setting-git-tag-from-azure-devops-build-pipeline-on-complete
# make sure the build service account is granted "Create Tag" and "Contribute" under repository security
- script: |
          git config --global user.name "AzureDevOps Agent"
          git tag "$(BuildVersionTag)" --force
          git push origin "$(buildVersionTag)" --force
          echo "Tagging $(Build.Repository.Name) with $(BuildVersionTag)"
  displayName: 'Tag Code'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
