# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
  - name: targetEnvironment
    displayName: Target Environment 
    type: string
    default: Test
    values:
    - Dev
    - Test

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  -group: Azure.Environment.Nucleus.Acc.Vue
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  apiservice:
   ${{if parameters.targetEnvironment == 'Dev'}}: 'nucleusaccnetdevapi'
   ${{if parameters.targetEnvironment == 'Test'}}: 'nucleusaccnetapi'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Building ${{ parameters.targetEnvironment }}'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Unit Tests...'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploying API to ${{ parameters.targetEnvironment }}'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'AppDev Project Nucleus'
    appType: 'webApp'
    WebAppName: '$(apiservice)'
    packageForLinux: '$(build.artifactStagingDirectory)\WebApp.zip'
