name: keycloak
services:
    keycloak:
        ports:
            - 8081:8080
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KEYCLOAK_IMPORT=./local-dev-realm.json
        volumes:
            - "./keycloak/:/opt/keycloak/data/import/"
        image: quay.io/keycloak/keycloak:latest
        command: start-dev --import-realm