name: azurite
services:
    azurite:
        container_name: azurite
        ports:
            - 10000:10000
            - 10001:10001
            - 10002:10002
        volumes:
            - "%cd%/azurite-scripts/:/opt/azurite/scripts/"
        networks:
            - dev-net
        image: mcr.microsoft.com/azure-storage/azurite
        command: >
          azurite 
          --blobPort 10000 --blobHost 0.0.0.0 
          --queuePort 10001 --queueHost 0.0.0.0 
          --tablePort 10002 --tableHost 0.0.0.0 
          --loose
          --skipApiVersionCheck 
          --disableProductStyleUrl
networks:
    dev-net:
        external: true
        name: dev-net