name: keycloak
services:
    keycloak:
        container_name: keycloak
        ports:
            - 8081:8080
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KEYCLOAK_IMPORT=./local-dev-realm.json
        volumes:
            - "%cd%/keycloak-import/:/opt/keycloak/data/import/"
        networks:
            - dev-net
        image: quay.io/keycloak/keycloak:latest
        command: start-dev --import-realm
networks:
    dev-net:
        external: true
        name: dev-net