name: smtp4dev
services:
    smtp4dev:
        container_name: smtp4dev
        ports:
            - 7777:80
            - 25:25
            - 143:143
            - 110:110
        networks:
            - dev-net
        image: rnwood/smtp4dev
networks:
    dev-net:
        external: true
        name: dev-net